# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on: [push,pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11


    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: install jq
      run:  sudo apt-get install -y jq

    - name: setup codacy version
      run:  echo "LATEST_CODACY_VERSION=$(curl -Ls https://api.bintray.com/packages/codacy/Binaries/codacy-coverage-reporter/versions/_latest | jq -r .name)" >> $GITHUB_ENV

    - name: echo codacy version
      run:  echo $LATEST_CODACY_VERSION


    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle

    - name: Build with Gradle
      run: ./gradlew build

    - name: Send report to codacy
      env:
        CODACY_API_TOKEN: ${{ secrets.CODACY_API_TOKEN }}
      run: |
        curl -Ls -o codacy-coverage-reporter "https://dl.bintray.com/codacy/Binaries/${LATEST_CODACY_VERSION}/codacy-coverage-reporter-linux"
        chmod +x codacy-coverage-reporter
        ./codacy-coverage-reporter report -l Java -r build/reports/jacoco/test/jacocoTestReport.xml




